version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_container
    ports:
      - "9004:3000"  # Exposing port for Next.js app
    networks:
      - nextjs_network

networks:
  nextjs_network:
    driver: bridge