# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package.json and package-lock.json
COPY package*.json ./
COPY .env .env
# Install dependencies
RUN pnpm install

# Copy the rest of the application
COPY . .

# Build the Next.js app
RUN pnpm run build

# Expose the port (use a unique port to avoid conflicts, e.g., 3001)
EXPOSE 3001



# Start the app
CMD ["pnpm", "start"]

